// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2LhZp8_Ult1WPXb06Mi9SXUF9qRm2MQ',
    appId: '1:695253026195:web:cdba1a52134db9dd369466',
    messagingSenderId: '695253026195',
    projectId: 'clothing-project-c92dc',
    authDomain: 'clothing-project-c92dc.firebaseapp.com',
    storageBucket: 'clothing-project-c92dc.appspot.com',
    measurementId: 'G-GLS3ZR6G0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC18Li89STGuOqnAgGVsQbxaAroKPnRtTI',
    appId: '1:695253026195:android:a1bf8b83a4dd7860369466',
    messagingSenderId: '695253026195',
    projectId: 'clothing-project-c92dc',
    storageBucket: 'clothing-project-c92dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqxex0o21H5hm2gWbz9h6TFA0d8M0SmgM',
    appId: '1:695253026195:ios:c02fc93c2f9a54e5369466',
    messagingSenderId: '695253026195',
    projectId: 'clothing-project-c92dc',
    storageBucket: 'clothing-project-c92dc.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqxex0o21H5hm2gWbz9h6TFA0d8M0SmgM',
    appId: '1:695253026195:ios:c02fc93c2f9a54e5369466',
    messagingSenderId: '695253026195',
    projectId: 'clothing-project-c92dc',
    storageBucket: 'clothing-project-c92dc.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf2LhZp8_Ult1WPXb06Mi9SXUF9qRm2MQ',
    appId: '1:695253026195:web:36e74d7fad802ee4369466',
    messagingSenderId: '695253026195',
    projectId: 'clothing-project-c92dc',
    authDomain: 'clothing-project-c92dc.firebaseapp.com',
    storageBucket: 'clothing-project-c92dc.appspot.com',
    measurementId: 'G-216WHKG9WD',
  );
}
